export const CATEGORY_RETRIEVE_DATA_BEGIN = "CATEGORY_RETRIEVE_DATA_BEGIN";
export const CATEGORY_RETRIEVE_DATA_SUCCESS = "CATEGORY_RETRIEVE_DATA_SUCCESS";
export const CATEGORY_RETRIEVE_DATA_FAILURE = "CATEGORY_RETRIEVE_DATA_FAILURE";
