export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_STORE_TOKENS_SUCCESS = "LOGIN_STORE_TOKENS_SUCCESS";
export const LOGIN_STORE_TOKENS_ERROR = "LOGIN_STORE_TOKENS_ERROR";
export const LOGOUT = "LOGOUT";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const REGISTER = "REGISTER";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const AUTH_ENABLED = "AUTH_ENABLED";
export const AUTH_ENABLED_ERROR = "AUTH_ENABLED_ERROR";
