export const ROUTE_RETRIEVE_DATA_BEGIN = "ROUTE_RETRIEVE_DATA_BEGIN";
export const ROUTE_RETRIEVE_DATA_SUCCESS = "ROUTE_RETRIEVE_DATA_SUCCESS";
export const ROUTE_RETRIEVE_DATA_FAILURE = "ROUTE_RETRIEVE_DATA_FAILURE";
