export const PRODUCT_RETRIEVE_DATA_BEGIN = "PRODUCT_RETRIEVE_DATA_BEGIN";
export const PRODUCT_RETRIEVE_DATA_SUCCESS = "PRODUCT_RETRIEVE_DATA_SUCCESS";
export const PRODUCT_RETRIEVE_DATA_FAILURE = "PRODUCT_RETRIEVE_DATA_FAILURE";
